# Site settings
title: A Voice For Leith Hill
header-img: img/banner.jpg
email: info@voiceforleithhill.co.uk
copyright_name:
description: "Non-party political community group committed to raising awareness and protesting against the proposed oil exploration at Leith Hill"
baseurl: ""
url: "http://www.voiceforleithhill.co.uk"
twitter_username:
github_username:
facebook_username:
email_username:
port: 4001

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-84292677-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
